config/routes.rb
Tula::Application.routes.draw do

  root :to => 'home#index'

  match '/coming-soon' => 'home#coming_soon', :as => :coming_soon
  match '/home' => 'home#index', :as => :home
  match '/about' => 'home#about', :as => :about
  match '/why-tula' => 'home#why', :as => :why
  match '/why-tula/acquired-companies' => 'home#acquisitions', :as => :acquisitions
  match '/why-tula/references' => 'home#references', :as => :references
  match '/investment-prospectus' => 'home#prospectus', :as => :prospectus
  match '/contact' => 'home#contact', :as => :contact
  match '/terms' => 'home#terms', :as => :terms
  match '/admin' => 'admin#index', :as => :admin
  post  '/users' => 'users#create'
  get   '/users/new' => 'users#new'
  get   '/users/login' => 'users#login', :as => :users_login
  post  '/users/login' => 'users#authenticate', :as => :users_authenticate
  get   '/users/logout' => 'users#logout', :as => :users_logout

  namespace :admin do
    resources :acquisitions
  end

  namespace :api do
    namespace :admin do
      resources :acquisitions
    end
  end

  ComfyBlog::Routing.admin
  ComfyBlog::Routing.content
  ComfortableMexicanSofa::Routing.admin(:path => '/cms-admin')
  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_hash, :password, :password_confirmation, :registered_at, :admin

  validates_confirmation_of :password
  validates_presence_of :email, :name, :password
  validates_uniqueness_of :email

  def encrypt_password(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

  def check_password?(entered_password)
    self.password == entered_password
  end

  def password
    @password ||= BCrypt::Password.new(self.password_hash)
  end

  def password=(new_password)
    encrypt_password(new_password)
  end

  def authenticate(password)
    check_password?(password)
  end

  def admin?
    !!admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    params[:user][:email].downcase!
    params[:user][:registered_at] = Time.now
    @user = User.new(params[:user])
    @user.last_login = Time.now

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def login
  end

  def logout
    session[:user_id] = nil
    redirect_to users_login_path, :alert => 'Logged out'
  end

  def authenticate
    user = User.find_by_email(params[:email].downcase)
    if user.nil?
      flash.alert = 'Email address is not registered'
      return render 'login'
    end

    if user.authenticate(params[:password])
      session[:user_id] = user.id
      user.last_login = Time.now
      user.save

      redirect_to root_url
    else
      flash.alert = 'Invalid password'
      render 'login'
    end
  end
end

app/views/users/login.html.haml
- body_id = 'login'
%title
  Log-In | TULA

#login_container
  - if flash[:alert]
    .alert.alert-warning#log-in-alert-notice
      %strong
        = flash[:alert]

  .row
    .col-md-4
      %h1
        Log In

  .row
    .col-md-3
      = form_tag users_authenticate_path do
        %p.form-group
          = label_tag :email, 'Email:', :class => 'control-label'
          = email_field_tag :email, nil, :class => 'form-control', :required => true
        %p.form-group
          = label_tag :password, 'Password:', :class => 'control-label'
          = password_field_tag :password, nil, :class => 'form-control', :required => true
        %p
          = submit_tag 'Log-In', :class => 'btn btn-primary'

  .row
    %span Don't have an account?
    = link_to 'Register!', users_new_path

app/views/users/new.html.haml
- body_id = 'sign-up'
%title
  Register | TULA

#signup_container
  .row
    .col-md-4
      %h1
        Sign Up
      - if @user.errors.any?
        .error-messages
          %h3 Could not register new user:
          %ul.list-group
            - for message in @user.errors.full_messages
              %li.list-group-item.list-group-item-danger
                = message

  .row
    .col-md-3
      = form_for @user, :url => users_path do |u|
        %p.form-group
          = u.label :name, 'Name:', :class => 'control-label'
          = u.text_field :name, :class => 'form-control', :required => true
        %p.form-group
          = u.label :email, 'Email:', :class => 'control-label'
          = u.email_field :email, :class => 'form-control', :required => true
        %p.form-group
          = u.label :password, 'Password:', :class => 'control-label'
          = u.password_field :password, :class => 'form-control', :required => true
        %p.form-group
          = u.label :password_confirmation, 'Confirm:', :class => 'control-label'
          = u.password_field :password_confirmation, :class => 'form-control', :required => true
        %p
          = u.submit 'Register', :class => 'btn btn-primary'

  .row
    %span Already registered?
    = link_to 'Login!', users_login_path