config/routes.rb
Tula::Application.routes.draw do

  root :to => 'home#index'

  match '/coming-soon' => 'home#coming_soon', :as => :coming_soon
  match '/home' => 'home#index', :as => :home
  match '/about' => 'home#about', :as => :about
  match '/why-tula' => 'home#why', :as => :why
  match '/why-tula/acquired-companies' => 'home#acquisitions', :as => :acquisitions
  match '/why-tula/references' => 'home#references', :as => :references
  match '/investment-prospectus' => 'home#prospectus', :as => :prospectus
  match '/contact' => 'home#contact', :as => :contact
  match '/terms' => 'home#terms', :as => :terms
  match '/admin' => 'admin#index', :as => :admin
  post  '/users' => 'users#create'
  get   '/users/new' => 'users#new'
  get   '/users/login' => 'users#login', :as => :users_login
  post  '/users/login' => 'users#authenticate', :as => :users_authenticate
  get   '/users/logout' => 'users#logout', :as => :users_logout

  namespace :admin do
    resources :acquisitions
  end

  namespace :api do
    namespace :admin do
      resources :acquisitions
    end
  end

  ComfyBlog::Routing.admin
  ComfyBlog::Routing.content
  ComfortableMexicanSofa::Routing.admin(:path => '/cms-admin')
  ComfortableMexicanSofa::Routing.content(:path => '/', :sitemap => false)

end

app/views/layouts/_footer.html.haml
#footer
  #foot_bar
    %ul
      %li#foot_home
        = link_to("Home", home_path)
      %li#foot_about
        = link_to("About", about_path)
      %li#foot_why
        = link_to("Why TULA", why_path)
      %li#foot_prospectus
        = link_to("Investment Prospectus", prospectus_path)
      %li#foot_contact
        = link_to("Contact", contact_path)
      %li#foot_blog
        = link_to("Blog", blog_posts_path)
  #foot_note
    Copyright #{"\u00A9"} TULA Investment Group, LLC 2018 - Created by 
    = link_to("David Gertmenian-Wong", "http://davidgw.com", :target => "blank")

app/views/layouts/_header.html.haml
#header
  #header_title
    #header_logo
      = link_to root_path do
        %h1
          %span TULA
          Investment Group
    #header_login
      - if current_user
        - if @current_user.admin?
          = link_to 'Admin', admin_path
          %span
            &nbsp|&nbsp
        = link_to 'Logout', users_logout_path
      - else
        = link_to 'Register', users_new_path
        %span
          &nbsp|&nbsp
        = link_to 'Login', users_login_path

  #nav_bar
    %ul
      = link_to home_path, :class => "#{active_class('home')}" do
        %li#nav_home Home
      = link_to about_path, :class => "#{active_class('about')}" do
        %li#nav_about About
      = link_to why_path, :class => "#{active_class('why')}" do
        %li#nav_why.has_sub_nav Why TULA
      = link_to prospectus_path, :class => "#{active_class('prospectus')}" do
        %li#nav_prospectus Prospectus
      = link_to contact_path, :class => "#{active_class('contact')}" do
        %li#nav_contact Contact
      = link_to blog_posts_path, :class => "#{active_class('blog')}" do
        %li#nav_blog Blog
      = link_to terms_path, :class => "#{active_class('terms')}" do
        %li#nav_terms Terms

app/views/layouts/_metas.html.haml
%link(rel="shortcut icon" href="assets/favicon.ico")

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    -# Meta tags
    = render 'layouts/metas'

    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/react/0.13.1/react.js'
    = javascript_include_tag 'application'
    = javascript_include_tag 'admin'
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'
    = stylesheet_link_tag 'admin'
    = yield :javascript_includes
    = csrf_meta_tags

  %body{:id => @body_id, :class => @body_class}
    #all_content
      #container
        %nav.navbar.navbar-default
          .container-fluid
            .navbar-header
              %a.navbar-brand{:href => admin_path} TULA Admin
            .collapse.navbar-collapse
              %ul.nav.navbar-nav
                %li
                  = link_to 'Acquisitions', admin_acquisitions_path
              %ul.nav.navbar-nav.navbar-right
                %li
                  = link_to 'Back to TULA', home_path
                %li
                  = link_to 'Log Out', users_logout_path
        #main
          .container-fluid
            = yield

app/views/layouts/application.html.haml
!!! 5
%html
  / (xmlns:giftrocket="http://www.giftrocket.com/ns#")
  / %head(prefix="og: http://ogp.me/ns# #{FB_APP_NAME}: http://ogp.me/ns/apps/#{FB_APP_NAME}#")
  /   <script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
  /   -# CSS + JS includes.
  /   = render 'layouts/includes'

  /   -# JS code to run.
  /   = render 'layouts/head_scripts'

  / -# The main point.
  / = render 'layouts/body'

  / -# Not too critical.
  / = render 'layouts/scripts_afterload'
  %head
    -# Meta tags
    = render 'layouts/metas'

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js'
    = javascript_include_tag 'application'
    = yield :javascript_includes
    = csrf_meta_tags
    %script
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55915372-2', 'auto');
      ga('send', 'pageview');

  %body{:id => @body_id, :class => @body_class}
    - if @comingsoon
      = yield
    - else
      #all_content
        #container
          - unless @noheader
            = render 'layouts/header'
          #main
            = yield
          = render 'layouts/footer'
        -# Keep footer out of container as background will repeat.
        -# See above note about header. Same applies.
        / = render 'layouts/footer'






/ <!DOCTYPE html>
/ <html>
/ <head>
/   <title>Tula</title>
/   <%= stylesheet_link_tag    "application", :media => "all" %>
/   <%= javascript_include_tag "application" %>
/   <%= csrf_meta_tags %>
/ </head>
/ <body>

/ <%= yield %>

/ </body>
/ </html>